CREATE TYPE "Payer" AS ENUM ('father', 'mother');
CREATE TYPE "ExpenseSource" AS ENUM ('rakuten', 'advance', 'personal');

CREATE TABLE "expenses" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "no" integer GENERATED BY DEFAULT AS IDENTITY,
  "accounting_month" varchar(7) NOT NULL,
  "date" date,
  "category" text NOT NULL DEFAULT '',
  "sub_category" text NOT NULL DEFAULT '',
  "item" text NOT NULL DEFAULT '',
  "description" text NOT NULL DEFAULT '',
  "amount" integer NOT NULL,
  "payer" "Payer" NOT NULL,
  "source" "ExpenseSource" NOT NULL,
  "reimbursed" boolean NOT NULL DEFAULT false,
  "beneficiary" text NOT NULL DEFAULT '',
  "comment" text NOT NULL DEFAULT '',
  "user_id" uuid,
  "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "expenses_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "deposits" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "no" integer GENERATED BY DEFAULT AS IDENTITY,
  "date" date NOT NULL,
  "depositor" "Payer" NOT NULL,
  "amount" integer NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "comment" text NOT NULL DEFAULT '',
  "user_id" uuid,
  "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "deposits_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "expenses_accounting_month_idx" ON "expenses"("accounting_month");
CREATE INDEX "expenses_payer_idx" ON "expenses"("payer");
CREATE INDEX "expenses_source_idx" ON "expenses"("source");
CREATE INDEX "deposits_date_idx" ON "deposits"("date");
CREATE INDEX "deposits_depositor_idx" ON "deposits"("depositor");

-- Supabase Auth導入後に有効化する想定。user_idに auth.users.id を入れてRLSで絞る。
-- ALTER TABLE "expenses" ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE "deposits" ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "expenses_select_own" ON "expenses" FOR SELECT USING (auth.uid() = user_id);
-- CREATE POLICY "expenses_insert_own" ON "expenses" FOR INSERT WITH CHECK (auth.uid() = user_id);
-- CREATE POLICY "expenses_update_own" ON "expenses" FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
-- CREATE POLICY "expenses_delete_own" ON "expenses" FOR DELETE USING (auth.uid() = user_id);
-- CREATE POLICY "deposits_select_own" ON "deposits" FOR SELECT USING (auth.uid() = user_id);
-- CREATE POLICY "deposits_insert_own" ON "deposits" FOR INSERT WITH CHECK (auth.uid() = user_id);
-- CREATE POLICY "deposits_update_own" ON "deposits" FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
-- CREATE POLICY "deposits_delete_own" ON "deposits" FOR DELETE USING (auth.uid() = user_id);
