'use client';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,Link2,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ExpenseRecord,ExpenseResponse,PAGE_SIZE,formatYen,formatExpenseDate} from '@/lib/expenses';
import {requestJson,errorMessage} from '@/lib/client-api';
export function ExpenseLinkPicker({initialMonth,sourceId,summary,onClose,onSelect}:{initialMonth:string;sourceId?:string;summary?:boolean;onClose:()=>void;onSelect:(expense:ExpenseRecord)=>Promise<void>}){
  const [month,setMonth]=useState(initialMonth);const [page,setPage]=useState(1);const [data,setData]=useState<ExpenseResponse|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{const c=new AbortController();setLoading(true);setError('');const params=new URLSearchParams({month,page:String(page)});if(sourceId)params.set('paymentSource',sourceId);requestJson<ExpenseResponse>('/api/expenses?'+params,{signal:c.signal}).then(result=>{if(!c.signal.aborted)setData(result);}).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[month,page,sourceId]);
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="expense-dialog master-dialog"><DialogHeader><DialogTitle>登録済みの支出を選択</DialogTitle><DialogDescription className="sr-only">既存の支出との紐づけ</DialogDescription></DialogHeader><div className="expense-form"><label htmlFor="link-month">支出月</label><input id="link-month" type="month" min="2000-01" max="2099-12" value={month} disabled={busy} onChange={e=>{if(/^20\d{2}-(0[1-9]|1[0-2])$/.test(e.target.value)){setMonth(e.target.value);setPage(1);}}} /></div>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<LoaderCircle className="animate-spin" />:<div className="link-candidates">{data?.expenses.map(e=><Button key={e.id} variant="ghost" disabled={busy||Boolean(summary&&e.summaryId)} onClick={async()=>{setBusy(true);setError('');try{await onSelect(e);onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><span><strong>{e.description||data.categories.find(c=>c.id===e.categoryId)?.name}</strong><small>{formatExpenseDate(e.date)}</small></span><strong>{formatYen(e.amount)}</strong><Link2 /></Button>)}{!data?.expenses.length&&<p className="workspace-message">支出の記録なし</p>}</div>}<div className="ledger-pagination"><Button variant="outline" size="icon" aria-label="候補の前ページ" disabled={busy||loading||page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft /></Button><span>{page} / {Math.max(1,Math.ceil((data?.filteredCount??0)/PAGE_SIZE))}</span><Button variant="outline" size="icon" aria-label="候補の次ページ" disabled={busy||loading||page*PAGE_SIZE>=(data?.filteredCount??0)} onClick={()=>setPage(p=>p+1)}><ChevronRight /></Button></div></DialogContent></Dialog>;
}
