'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Clock3,Link2,Pencil,Plus,Save,Undo2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ExpenseRecord,formatExpenseDate,formatYen} from '@/lib/expenses';
import {Masters} from '@/lib/ledger';
import {draftRecord,newExpense,paymentSourceGroups,paymentSuggestion} from '@/lib/household';
import {PlanFields,PlanRecord,planFields,planIsActionable,planReviewDate} from '@/lib/planning';
import {requestJson,errorMessage} from '@/lib/client-api';
import {CategorySelect} from './CategorySelect';
import {ReferenceSelect} from './ReferenceSelect';
import {ExpenseEditor} from './ExpenseEditor';
import {SnoozeDialog} from './SnoozeDialog';
import {ExpenseLinkPicker} from './ExpenseLinkPicker';

export function PlansWorkspace({month,masters,revision,onChanged,onEdit,onMastersChanged}:{month:string;masters:Masters;revision:number;onChanged:()=>void;onEdit:(expense:ExpenseRecord)=>void;onMastersChanged:(masters:Masters)=>void}){
  const [plans,setPlans]=useState<PlanRecord[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [editing,setEditing]=useState<{plan:PlanRecord|null}|null>(null);
  const [confirming,setConfirming]=useState<PlanRecord|null>(null);const [linking,setLinking]=useState<PlanRecord|null>(null);const [snoozing,setSnoozing]=useState<PlanRecord|null>(null);const [history,setHistory]=useState(false);const [busy,setBusy]=useState(false);const lock=useRef(false);
  useEffect(()=>{const c=new AbortController();setLoading(true);requestJson<PlanRecord[]>('/api/plans',{signal:c.signal}).then(rows=>{if(!c.signal.aborted)setPlans(rows);}).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[revision]);
  async function action(plan:PlanRecord,action:'cancel'|'reopen'|'edit'){
    if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(action==='edit')onEdit(await requestJson<ExpenseRecord>('/api/expenses/'+plan.expenseId));else{await requestJson('/api/plans/'+plan.id,{method:'POST',body:JSON.stringify({action,version:plan.version})});onChanged();}}catch(e){setError(errorMessage(e));}finally{lock.current=false;setBusy(false);}
  }
  const visible=plans.filter(p=>history||p.state==='open');
  const confirmationDefaults=confirming?newExpense(masters,confirming.date):null;
  const confirmationCategory=confirming?.categoryId??confirmationDefaults?.categoryId;
  const confirmationDraft=confirming&&confirmationDefaults?draftRecord({...confirmationDefaults,amount:confirming.amount??0,categoryId:confirmationCategory!,costClass:masters.categories.find(c=>c.id===confirmationCategory)?.costClass??'unknown',description:confirming.name,memo:confirming.memo,...paymentSuggestion(masters,confirming.paymentSourceId??confirmationDefaults.paymentSourceId!,confirming.amount??0)}):undefined;
  return <section className="plans-workspace"><div className="workspace-heading"><h2>単発の予定</h2><Button className="primary-action" disabled={loading} onClick={()=>setEditing({plan:null})}><Plus />予定を追加</Button></div><label className="check-label"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)} />確定・中止済みも表示</label>{error&&<p className="form-error" role="alert">{error}</p>}{loading?<p className="workspace-message">予定を読み込み中</p>:!visible.length?<p className="workspace-message">予定なし</p>:<ul className="recurring-list">{visible.map(plan=><li key={plan.id}><div className="recurring-item-main"><div><strong>{plan.name}</strong><small>{formatExpenseDate(plan.date)}</small><small>確認開始 {planReviewDate(plan)}</small></div><div className="recurring-amount"><strong>{plan.amount===null?'金額未定':formatYen(plan.amount)}</strong><span>{plan.state==='posted'?'登録済み':plan.state==='cancelled'?'中止':planIsActionable(plan)?'確認待ち':'予定'}</span></div></div><div className="recurring-actions">{plan.state==='posted'?<Button variant="outline" disabled={busy} onClick={()=>action(plan,'edit')}>登録済みの支出</Button>:<><Button variant="ghost" size="icon" title="予定を編集" aria-label={plan.name+'の予定を編集'} disabled={busy} onClick={()=>setEditing({plan})}><Pencil /></Button>{plan.state==='cancelled'?<Button variant="outline" disabled={busy} onClick={()=>action(plan,'reopen')}><Undo2 />中止取消</Button>:<><Button variant="ghost" size="icon" title="予定を中止" aria-label={plan.name+'を中止'} disabled={busy} onClick={()=>{if(window.confirm(plan.name+'を中止しますか？'))action(plan,'cancel');}}><X /></Button><Button variant="ghost" size="icon" title="確認を後日にする" aria-label={plan.name+'の確認を後日にする'} disabled={busy} onClick={()=>setSnoozing(plan)}><Clock3 /></Button><Button variant="ghost" size="icon" title="登録済みの支出と紐づけ" aria-label={plan.name+'を登録済みの支出と紐づけ'} disabled={busy} onClick={()=>setLinking(plan)}><Link2 /></Button><Button variant="outline" disabled={busy} onClick={()=>setConfirming(plan)}><Plus />支出を確定</Button></>}</>}</div></li>)}</ul>}
    {editing&&<PlanEditor key={editing.plan?.id??'new'} plan={editing.plan} month={month} masters={masters} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);onChanged();}} />}
    {confirming&&<ExpenseEditor title={confirming.name+'を確定'} expense={null} initial={confirmationDraft} initialMonth={month} masters={masters} onMastersChanged={onMastersChanged} onClose={()=>setConfirming(null)} onDelete={()=>{}} onDuplicate={()=>{}} onSaved={()=>{setConfirming(null);onChanged();}} saveOverride={(expenseId,expense)=>requestJson('/api/plans/'+confirming.id,{method:'POST',body:JSON.stringify({action:'post',version:confirming.version,expenseId,expense})})} />}
    {snoozing&&<SnoozeDialog name={snoozing.name} onClose={()=>setSnoozing(null)} onSave={async until=>{await requestJson('/api/plans/'+snoozing.id,{method:'POST',body:JSON.stringify({action:'snooze',version:snoozing.version,until})});onChanged();}} />}
    {linking&&<ExpenseLinkPicker initialMonth={linking.date.slice(0,7)} onClose={()=>setLinking(null)} onSelect={async expense=>{await requestJson('/api/plans/'+linking.id,{method:'POST',body:JSON.stringify({action:'link',version:linking.version,expenseId:expense.id,expenseVersion:expense.version})});onChanged();}} />}
  </section>;
}

function PlanEditor({plan,month,masters,onClose,onSaved}:{plan:PlanRecord|null;month:string;masters:Masters;onClose:()=>void;onSaved:()=>void}){
  const [id]=useState(()=>plan?.id??crypto.randomUUID());const [fields,setFields]=useState<PlanFields>(()=>plan?planFields.strip().parse(plan):{name:'',date:month,amount:null,categoryId:null,paymentSourceId:null,memo:'',reviewAfter:null});const [monthOnly,setMonthOnly]=useState(fields.date.length===7);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const baseline=useRef(JSON.stringify(fields));const lock=useRef(false);
  const patch=(value:Partial<PlanFields>)=>setFields(old=>({...old,...value}));
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(baseline.current!==JSON.stringify(fields)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[fields]);
  function close(){if(!busy&&(baseline.current===JSON.stringify(fields)||window.confirm('入力中の変更を破棄しますか？')))onClose();}
  async function save(e:FormEvent){e.preventDefault();if(lock.current)return;const parsed=planFields.safeParse(fields);if(!parsed.success){setError('予定の名称・日付・金額を確認してください。');return;}lock.current=true;setBusy(true);setError('');try{await requestJson(plan?'/api/plans/'+id:'/api/plans',{method:plan?'PUT':'POST',body:JSON.stringify({...parsed.data,...(plan?{version:plan.version}:{id})})});onSaved();}catch(e){setError(errorMessage(e));}finally{lock.current=false;setBusy(false);}}
  return <Dialog open onOpenChange={open=>{if(!open)close();}}><DialogContent className="expense-dialog expense-entry-dialog" onInteractOutside={e=>e.preventDefault()}><DialogHeader><DialogTitle>{plan?'予定を編集':'予定を追加'}</DialogTitle><DialogDescription className="sr-only">単発の支出予定</DialogDescription></DialogHeader><form id={'plan-'+id} className="expense-form" onSubmit={save}><label htmlFor="plan-name">名称</label><input id="plan-name" required maxLength={120} value={fields.name} disabled={busy} onChange={e=>patch({name:e.target.value})} /><fieldset disabled={busy}><legend>予定日</legend><div className="date-mode"><label><input type="radio" checked={!monthOnly} name="plan-date-mode" onChange={()=>{setMonthOnly(false);patch({date:fields.date+'-01'});}} /><span>日付指定</span></label><label><input type="radio" checked={monthOnly} name="plan-date-mode" onChange={()=>{setMonthOnly(true);patch({date:fields.date.slice(0,7)});}} /><span>月のみ</span></label></div><input aria-label="予定日" type={monthOnly?'month':'date'} required min={monthOnly?'2000-01':'2000-01-01'} max={monthOnly?'2099-12':'2099-12-31'} value={fields.date} onChange={e=>patch({date:e.target.value})} /></fieldset><label htmlFor="plan-amount">予定額（円） <span className="muted-text">任意</span></label><input id="plan-amount" inputMode="numeric" maxLength={9} value={fields.amount??''} disabled={busy} onChange={e=>{if(/^\d*$/.test(e.target.value))patch({amount:e.target.value?Number(e.target.value):null});}} /><label>カテゴリ <span className="muted-text">任意</span></label><CategorySelect label="予定のカテゴリ" value={fields.categoryId??''} optional categories={masters.categories} onChange={categoryId=>patch({categoryId:categoryId||null})} disabled={busy} /><label>支払元 <span className="muted-text">任意</span></label><ReferenceSelect label="予定の支払元" value={fields.paymentSourceId} emptyLabel="未定" options={[]} groups={paymentSourceGroups(masters,fields.paymentSourceId)} onChange={paymentSourceId=>patch({paymentSourceId})} disabled={busy} /><label htmlFor="plan-review">確認開始日 <span className="muted-text">任意</span></label><input id="plan-review" type="date" min="2000-01-01" max="2099-12-31" value={fields.reviewAfter??''} disabled={busy} onChange={e=>patch({reviewAfter:e.target.value||null})} /><label htmlFor="plan-memo">メモ</label><textarea id="plan-memo" rows={2} maxLength={1000} value={fields.memo} disabled={busy} onChange={e=>patch({memo:e.target.value})} />{error&&<p className="form-error" role="alert">{error}</p>}</form><div className="editor-save"><Button type="button" variant="outline" disabled={busy} onClick={close}>キャンセル</Button><Button form={'plan-'+id} type="submit" className="primary-action" disabled={busy}><Save />保存</Button></div></DialogContent></Dialog>;
}
