'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Check,Link2,Pencil,Plus,Save,Trash2,Unlink} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ExpenseRecord,formatExpenseDate,formatYen} from '@/lib/expenses';
import {Masters} from '@/lib/ledger';
import {draftRecord,newExpense,paymentSourceGroups,paymentSuggestion} from '@/lib/household';
import {SummaryFields,SummaryRecord,summaryFields} from '@/lib/planning';
import {requestJson,errorMessage} from '@/lib/client-api';
import {ReferenceSelect} from './ReferenceSelect';
import {ExpenseEditor} from './ExpenseEditor';
import {ExpenseLinkPicker} from './ExpenseLinkPicker';

export function SummaryWorkspace({month,masters,revision,onChanged,onEdit,onMastersChanged}:{month:string;masters:Masters;revision:number;onChanged:()=>void;onEdit:(row:ExpenseRecord)=>void;onMastersChanged:(masters:Masters)=>void}){
  const [rows,setRows]=useState<SummaryRecord[]>([]);const [error,setError]=useState('');const [editing,setEditing]=useState<{summary:SummaryRecord|null}|null>(null);const [selected,setSelected]=useState<string|null>(null);
  useEffect(()=>{const c=new AbortController();setError('');setRows([]);requestJson<SummaryRecord[]>('/api/summaries?month='+month,{signal:c.signal}).then(rows=>{if(!c.signal.aborted)setRows(rows);}).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));});return()=>c.abort();},[month,revision]);
  return <section className="summary-workspace" aria-label="まとめ記録"><div className="ledger-heading"><h2>まとめ記録</h2><Button variant="outline" onClick={()=>setEditing({summary:null})}><Plus />まとめて登録</Button></div>{error&&<p className="form-error" role="alert">{error}</p>}{rows.length>0&&<ul className="summary-list">{rows.map(row=><li key={row.id}><button type="button" className="summary-row" onClick={()=>setSelected(row.id)}><span><strong>{row.name}</strong><small>{masters.paymentSources.find(s=>s.id===row.paymentSourceId)?.name} · {row.complete?'まとめ記録で完了':row.remainder===0?'明細化済み':'明細未整理'}</small></span><span><strong>{formatYen(row.amount)}</strong><small>未整理 {formatYen(row.remainder)}</small></span></button></li>)}</ul>}
    {editing&&<SummaryEditor key={editing.summary?.id??'new'} summary={editing.summary} month={month} masters={masters} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);onChanged();}} />}
    {selected&&<SummaryDetail id={selected} month={month} masters={masters} revision={revision} onChanged={onChanged} onClose={()=>setSelected(null)} onMastersChanged={onMastersChanged} onEditExpense={row=>{setSelected(null);onEdit(row);}} onEditSummary={summary=>{setSelected(null);setEditing({summary});}} />}
  </section>;
}
function SummaryEditor({summary,month,masters,onClose,onSaved}:{summary:SummaryRecord|null;month:string;masters:Masters;onClose:()=>void;onSaved:()=>void}){
  const [id]=useState(()=>summary?.id??crypto.randomUUID());const [fields,setFields]=useState<SummaryFields>(()=>summary?summaryFields.strip().parse(summary):{name:'カード利用分',month,amount:0,paymentSourceId:masters.paymentSources.find(s=>s.isDefault&&!s.archived)?.id??'',memo:'',complete:true});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const baseline=useRef(JSON.stringify(fields));const lock=useRef(false);
  const patch=(input:Partial<SummaryFields>)=>setFields(old=>({...old,...input}));
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(baseline.current!==JSON.stringify(fields)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[fields]);
  function close(){if(!busy&&(baseline.current===JSON.stringify(fields)||window.confirm('入力中の変更を破棄しますか？')))onClose();}
  async function save(e:FormEvent){e.preventDefault();if(lock.current)return;const parsed=summaryFields.safeParse(fields);if(!parsed.success){setError('名称・計上月・支払元・金額を確認してください。');return;}if(summary&&summary.month!==fields.month&&!window.confirm('未整理額の計上月が変わり、月別の合計が変わります。変更しますか？'))return;lock.current=true;setBusy(true);setError('');try{await requestJson(summary?'/api/summaries/'+id:'/api/summaries',{method:summary?'PUT':'POST',body:JSON.stringify({...parsed.data,...(summary?{version:summary.version}:{id})})});onSaved();}catch(e){setError(errorMessage(e));}finally{lock.current=false;setBusy(false);}}
  return <Dialog open onOpenChange={open=>{if(!open)close();}}><DialogContent className="expense-dialog expense-entry-dialog" onInteractOutside={e=>e.preventDefault()}><DialogHeader><DialogTitle>{summary?'まとめ記録を編集':'まとめて登録'}</DialogTitle><DialogDescription className="sr-only">支出の概算・未整理額</DialogDescription></DialogHeader><form id={'summary-'+id} className="expense-form" onSubmit={save}><label htmlFor="summary-name">名称</label><input id="summary-name" required maxLength={120} value={fields.name} disabled={busy} onChange={e=>patch({name:e.target.value})} /><label>支払元</label><ReferenceSelect label="まとめ記録の支払元" value={fields.paymentSourceId} emptyLabel="選択してください" options={[]} groups={paymentSourceGroups(masters,fields.paymentSourceId)} disabled={busy} onChange={paymentSourceId=>patch({paymentSourceId:paymentSourceId??''})} /><label htmlFor="summary-month">計上月</label><input id="summary-month" type="month" min="2000-01" max="2099-12" required value={fields.month} disabled={busy} onChange={e=>patch({month:e.target.value})} /><label htmlFor="summary-amount">家計の支出額（円）</label><input id="summary-amount" required inputMode="numeric" maxLength={9} value={fields.amount||''} disabled={busy} onChange={e=>{if(/^\d*$/.test(e.target.value))patch({amount:Number(e.target.value)});}} /><label className="check-label"><input type="checkbox" checked={fields.complete} disabled={busy} onChange={e=>patch({complete:e.target.checked})} />今回はまとめ記録で完了</label><label htmlFor="summary-memo">メモ</label><textarea id="summary-memo" rows={2} maxLength={1000} value={fields.memo} disabled={busy} onChange={e=>patch({memo:e.target.value})} />{error&&<p className="form-error" role="alert">{error}</p>}</form><div className="editor-save"><Button variant="outline" disabled={busy} onClick={close}>キャンセル</Button><Button form={'summary-'+id} type="submit" className="primary-action" disabled={busy}><Save />保存</Button></div></DialogContent></Dialog>;
}
type Detail={summary:SummaryRecord;details:ExpenseRecord[]};
function SummaryDetail({id,month,masters,revision,onChanged,onClose,onEditExpense,onEditSummary,onMastersChanged}:{id:string;month:string;masters:Masters;revision:number;onChanged:()=>void;onClose:()=>void;onEditExpense:(row:ExpenseRecord)=>void;onEditSummary:(row:SummaryRecord)=>void;onMastersChanged:(masters:Masters)=>void}){
  const [data,setData]=useState<Detail|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [linking,setLinking]=useState(false);const [creating,setCreating]=useState(false);const lock=useRef(false);
  useEffect(()=>{const c=new AbortController();requestJson<Detail>('/api/summaries/'+id+'?month='+month,{signal:c.signal}).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(errorMessage(e));});return()=>c.abort();},[id,month,revision]);
  const summary=data?.summary;
  function allowMonthChange(date:string){return date.slice(0,7)!==summary?.month&&window.confirm('計上月が異なります。未整理額は減り、明細は実際の支出月に計上されるため月別合計が変わります。紐づけますか？');}
  async function mutate(action:()=>Promise<unknown>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action();onChanged();}catch(e){setError(errorMessage(e));}finally{lock.current=false;setBusy(false);}}
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="expense-dialog master-dialog"><DialogHeader><DialogTitle>{summary?.name??'まとめ記録'}</DialogTitle><DialogDescription>{summary?summary.month+' / '+(masters.paymentSources.find(s=>s.id===summary.paymentSourceId)?.name??''):''}</DialogDescription></DialogHeader>{error&&<p className="form-error" role="alert">{error}</p>}{summary&&data&&<><dl className="summary-amounts"><div><dt>総額</dt><dd>{formatYen(summary.amount)}</dd></div><div><dt>明細化済み</dt><dd>{formatYen(summary.detailedAmount)}</dd></div><div><dt>未整理</dt><dd>{formatYen(summary.remainder)}</dd></div></dl><div className="recurring-actions"><Button variant="ghost" size="icon" title="まとめ記録を編集" aria-label="まとめ記録を編集" disabled={busy} onClick={()=>onEditSummary(summary)}><Pencil /></Button><Button variant="ghost" size="icon" title="まとめ記録を削除" aria-label="まとめ記録を削除" disabled={busy||summary.detailCount>0} onClick={()=>{if(window.confirm('まとめ記録を削除すると、未整理額が支出合計から除かれます。削除しますか？'))mutate(async()=>{await requestJson('/api/summaries/'+id,{method:'DELETE',body:JSON.stringify({version:summary.version})});onClose();});}}><Trash2 /></Button><Button variant="outline" disabled={busy} onClick={()=>setLinking(true)}><Link2 />登録済みから</Button><Button variant="outline" disabled={busy||summary.remainder===0} onClick={()=>setCreating(true)}><Plus />明細を追加</Button></div>{summary.complete&&<p className="summary-complete"><Check />まとめ記録で完了</p>}<div className="summary-details">{data.details.map(expense=><div key={expense.id}><button type="button" className="summary-row" disabled={busy} onClick={()=>onEditExpense(expense)}><span><strong>{expense.description||masters.categories.find(c=>c.id===expense.categoryId)?.name}</strong><small>{formatExpenseDate(expense.date)}</small></span><strong>{formatYen(expense.amount)}</strong></button><Button variant="ghost" size="icon" title="紐づけを解除" aria-label={(expense.description||'明細')+'の紐づけを解除'} disabled={busy} onClick={()=>{if(window.confirm('明細は支出に残り、まとめ記録の未整理額も増えます。解除しますか？'))mutate(()=>requestJson('/api/summaries/'+id,{method:'POST',body:JSON.stringify({action:'unlink',version:summary.version,expenseId:expense.id,expenseVersion:expense.version})}));}}><Unlink /></Button></div>)}</div></>}
    {linking&&summary&&<ExpenseLinkPicker summary sourceId={summary.paymentSourceId} initialMonth={summary.month} onClose={()=>setLinking(false)} onSelect={async expense=>{const allow=allowMonthChange(expense.date);if(expense.date.slice(0,7)!==summary.month&&!allow)throw new Error('紐づけをキャンセルしました。');await requestJson('/api/summaries/'+id,{method:'POST',body:JSON.stringify({action:'link',version:summary.version,expenseId:expense.id,expenseVersion:expense.version,allowMonthChange:allow})});onChanged();}} />}
    {creating&&summary&&<ExpenseEditor title="まとめ記録の明細を追加" expense={null} initial={draftRecord({...newExpense(masters,summary.month),...paymentSuggestion(masters,summary.paymentSourceId,0)})} initialMonth={summary.month} masters={masters} onMastersChanged={onMastersChanged} onClose={()=>setCreating(false)} onSaved={()=>{setCreating(false);onChanged();}} onDelete={()=>{}} onDuplicate={()=>{}} saveOverride={async(expenseId,expense)=>{const allow=allowMonthChange(expense.date);if(expense.date.slice(0,7)!==summary.month&&!allow)throw new Error('保存をキャンセルしました。');return requestJson('/api/summaries/'+id,{method:'POST',body:JSON.stringify({action:'create-detail',version:summary.version,expenseId,expense,allowMonthChange:allow})});}} />}
  </DialogContent></Dialog>;
}
